# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_content_audio_dto import ExerciseContentAudioDto

class TestExerciseContentAudioDto(unittest.TestCase):
    """ExerciseContentAudioDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseContentAudioDto:
        """Test ExerciseContentAudioDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseContentAudioDto`
        """
        model = ExerciseContentAudioDto()
        if include_optional:
            return ExerciseContentAudioDto(
                audio_url = ''
            )
        else:
            return ExerciseContentAudioDto(
                audio_url = '',
        )
        """

    def testExerciseContentAudioDto(self):
        """Test ExerciseContentAudioDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
