# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.write_placeholders_feedback_dto import WritePlaceholdersFeedbackDto

class TestWritePlaceholdersFeedbackDto(unittest.TestCase):
    """WritePlaceholdersFeedbackDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WritePlaceholdersFeedbackDto:
        """Test WritePlaceholdersFeedbackDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WritePlaceholdersFeedbackDto`
        """
        model = WritePlaceholdersFeedbackDto()
        if include_optional:
            return WritePlaceholdersFeedbackDto(
                correct_placeholders_ids = [
                    ''
                    ],
                incorrect_placeholders_ids = [
                    ''
                    ]
            )
        else:
            return WritePlaceholdersFeedbackDto(
                correct_placeholders_ids = [
                    ''
                    ],
                incorrect_placeholders_ids = [
                    ''
                    ],
        )
        """

    def testWritePlaceholdersFeedbackDto(self):
        """Test WritePlaceholdersFeedbackDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
