# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.vocabulary_controller_api import VocabularyControllerApi


class TestVocabularyControllerApi(unittest.TestCase):
    """VocabularyControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VocabularyControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get(self) -> None:
        """Test case for get

        """
        pass


if __name__ == '__main__':
    unittest.main()
