# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pair_option_feedback_pair import PairOptionFeedbackPair

class TestPairOptionFeedbackPair(unittest.TestCase):
    """PairOptionFeedbackPair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PairOptionFeedbackPair:
        """Test PairOptionFeedbackPair
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PairOptionFeedbackPair`
        """
        model = PairOptionFeedbackPair()
        if include_optional:
            return PairOptionFeedbackPair(
                left_id = '',
                right_id = ''
            )
        else:
            return PairOptionFeedbackPair(
                left_id = '',
                right_id = '',
        )
        """

    def testPairOptionFeedbackPair(self):
        """Test PairOptionFeedbackPair"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
