# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.configuration_controller_api import ConfigurationControllerApi


class TestConfigurationControllerApi(unittest.TestCase):
    """ConfigurationControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_all3(self) -> None:
        """Test case for get_all3

        """
        pass


if __name__ == '__main__':
    unittest.main()
