# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.flashcard_controller_api import FlashcardControllerApi


class TestFlashcardControllerApi(unittest.TestCase):
    """FlashcardControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlashcardControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        """
        pass

    def test_create_rich(self) -> None:
        """Test case for create_rich

        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        """
        pass

    def test_get_all1(self) -> None:
        """Test case for get_all1

        """
        pass

    def test_update(self) -> None:
        """Test case for update

        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        """
        pass


if __name__ == '__main__':
    unittest.main()
