# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.configuration_google_text_to_speech_dto import ConfigurationGoogleTextToSpeechDto

class TestConfigurationGoogleTextToSpeechDto(unittest.TestCase):
    """ConfigurationGoogleTextToSpeechDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationGoogleTextToSpeechDto:
        """Test ConfigurationGoogleTextToSpeechDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationGoogleTextToSpeechDto`
        """
        model = ConfigurationGoogleTextToSpeechDto()
        if include_optional:
            return ConfigurationGoogleTextToSpeechDto(
                language_code = '',
                voice_name = ''
            )
        else:
            return ConfigurationGoogleTextToSpeechDto(
        )
        """

    def testConfigurationGoogleTextToSpeechDto(self):
        """Test ConfigurationGoogleTextToSpeechDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
