# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.exercise_controller_api import ExerciseControllerApi


class TestExerciseControllerApi(unittest.TestCase):
    """ExerciseControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExerciseControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get3(self) -> None:
        """Test case for get3

        """
        pass

    def test_get4(self) -> None:
        """Test case for get4

        """
        pass

    def test_get_types(self) -> None:
        """Test case for get_types

        """
        pass

    def test_submit_answer(self) -> None:
        """Test case for submit_answer

        """
        pass

    def test_submit_answer_rich(self) -> None:
        """Test case for submit_answer_rich

        """
        pass


if __name__ == '__main__':
    unittest.main()
