# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_session_options_review_flashcards_dto import ExerciseSessionOptionsReviewFlashcardsDto

class TestExerciseSessionOptionsReviewFlashcardsDto(unittest.TestCase):
    """ExerciseSessionOptionsReviewFlashcardsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseSessionOptionsReviewFlashcardsDto:
        """Test ExerciseSessionOptionsReviewFlashcardsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseSessionOptionsReviewFlashcardsDto`
        """
        model = ExerciseSessionOptionsReviewFlashcardsDto()
        if include_optional:
            return ExerciseSessionOptionsReviewFlashcardsDto(
                initial_flashcard_language_id = '',
                available_flashcard_languages = [
                    openapi_client.models.exercise_session_options_language_option_dto.ExerciseSessionOptionsLanguageOptionDto(
                        id = '', 
                        iso_code = '', )
                    ]
            )
        else:
            return ExerciseSessionOptionsReviewFlashcardsDto(
        )
        """

    def testExerciseSessionOptionsReviewFlashcardsDto(self):
        """Test ExerciseSessionOptionsReviewFlashcardsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
