# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.select_options_input_feedback_dto import SelectOptionsInputFeedbackDto

class TestSelectOptionsInputFeedbackDto(unittest.TestCase):
    """SelectOptionsInputFeedbackDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelectOptionsInputFeedbackDto:
        """Test SelectOptionsInputFeedbackDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SelectOptionsInputFeedbackDto`
        """
        model = SelectOptionsInputFeedbackDto()
        if include_optional:
            return SelectOptionsInputFeedbackDto(
                correct_option_ids = [
                    ''
                    ],
                incorrect_option_ids = [
                    ''
                    ],
                is_retype_answer_enabled = True
            )
        else:
            return SelectOptionsInputFeedbackDto(
                correct_option_ids = [
                    ''
                    ],
                incorrect_option_ids = [
                    ''
                    ],
        )
        """

    def testSelectOptionsInputFeedbackDto(self):
        """Test SelectOptionsInputFeedbackDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
