# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.submit_answer_request import SubmitAnswerRequest

class TestSubmitAnswerRequest(unittest.TestCase):
    """SubmitAnswerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitAnswerRequest:
        """Test SubmitAnswerRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitAnswerRequest`
        """
        model = SubmitAnswerRequest()
        if include_optional:
            return SubmitAnswerRequest(
                id = '',
                type = '',
                url = '',
                feedback = openapi_client.models.exercise_input_feedback_text_dto.ExerciseInputFeedbackTextDto(
                    correct_values = [
                        ''
                        ], 
                    incorrect_values = [
                        ''
                        ], ),
                options = [
                    openapi_client.models.option.Option(
                        id = '', 
                        text = '', )
                    ],
                value = '',
                rating = '',
                text = ''
            )
        else:
            return SubmitAnswerRequest(
        )
        """

    def testSubmitAnswerRequest(self):
        """Test SubmitAnswerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
