# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_session_options_learn_flashcards_dto import ExerciseSessionOptionsLearnFlashcardsDto

class TestExerciseSessionOptionsLearnFlashcardsDto(unittest.TestCase):
    """ExerciseSessionOptionsLearnFlashcardsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseSessionOptionsLearnFlashcardsDto:
        """Test ExerciseSessionOptionsLearnFlashcardsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseSessionOptionsLearnFlashcardsDto`
        """
        model = ExerciseSessionOptionsLearnFlashcardsDto()
        if include_optional:
            return ExerciseSessionOptionsLearnFlashcardsDto(
                answer_language_ids = [
                    ''
                    ],
                available_answer_language_ids = [
                    ''
                    ],
                retype_correct_answer_enabled = True
            )
        else:
            return ExerciseSessionOptionsLearnFlashcardsDto(
        )
        """

    def testExerciseSessionOptionsLearnFlashcardsDto(self):
        """Test ExerciseSessionOptionsLearnFlashcardsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
