# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_feedback_dto import ExerciseFeedbackDto

class TestExerciseFeedbackDto(unittest.TestCase):
    """ExerciseFeedbackDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseFeedbackDto:
        """Test ExerciseFeedbackDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseFeedbackDto`
        """
        model = ExerciseFeedbackDto()
        if include_optional:
            return ExerciseFeedbackDto(
                type = '',
                state = '',
                message = ''
            )
        else:
            return ExerciseFeedbackDto(
        )
        """

    def testExerciseFeedbackDto(self):
        """Test ExerciseFeedbackDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
