# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flashcard_dto import FlashcardDto

class TestFlashcardDto(unittest.TestCase):
    """FlashcardDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlashcardDto:
        """Test FlashcardDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlashcardDto`
        """
        model = FlashcardDto()
        if include_optional:
            return FlashcardDto(
                id = '',
                deck_id = '',
                deck_order = 56,
                front_content = None,
                back_content = None
            )
        else:
            return FlashcardDto(
                id = '',
        )
        """

    def testFlashcardDto(self):
        """Test FlashcardDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
