# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_multiple_choice_text_dto import ExerciseInputMultipleChoiceTextDto

class TestExerciseInputMultipleChoiceTextDto(unittest.TestCase):
    """ExerciseInputMultipleChoiceTextDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputMultipleChoiceTextDto:
        """Test ExerciseInputMultipleChoiceTextDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputMultipleChoiceTextDto`
        """
        model = ExerciseInputMultipleChoiceTextDto()
        if include_optional:
            return ExerciseInputMultipleChoiceTextDto(
                feedback = openapi_client.models.exercise_input_feedback_multiple_choice_text_feedback_dto.ExerciseInputFeedbackMultipleChoiceTextFeedbackDto(
                    correct_option_ids = [
                        ''
                        ], 
                    incorrect_option_ids = [
                        ''
                        ], ),
                options = [
                    openapi_client.models.option.Option(
                        id = '', 
                        text = '', )
                    ],
                value = ''
            )
        else:
            return ExerciseInputMultipleChoiceTextDto(
        )
        """

    def testExerciseInputMultipleChoiceTextDto(self):
        """Test ExerciseInputMultipleChoiceTextDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
