# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flashcard_dto_front_content import FlashcardDtoFrontContent

class TestFlashcardDtoFrontContent(unittest.TestCase):
    """FlashcardDtoFrontContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlashcardDtoFrontContent:
        """Test FlashcardDtoFrontContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlashcardDtoFrontContent`
        """
        model = FlashcardDtoFrontContent()
        if include_optional:
            return FlashcardDtoFrontContent(
                id = '',
                type = '',
                audio_url = '',
                image_url = '',
                text = '',
                language_id = '',
                audio_file_name = '',
                image_file_name = '',
                video_file_name = '',
                video_url = ''
            )
        else:
            return FlashcardDtoFrontContent(
        )
        """

    def testFlashcardDtoFrontContent(self):
        """Test FlashcardDtoFrontContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
