# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_select_options_dto import ExerciseInputSelectOptionsDto

class TestExerciseInputSelectOptionsDto(unittest.TestCase):
    """ExerciseInputSelectOptionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputSelectOptionsDto:
        """Test ExerciseInputSelectOptionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputSelectOptionsDto`
        """
        model = ExerciseInputSelectOptionsDto()
        if include_optional:
            return ExerciseInputSelectOptionsDto(
                options = [
                    openapi_client.models.select_option_input_base_option.SelectOptionInputBaseOption(
                        id = '', )
                    ],
                option_type = '',
                value = '',
                feedback = openapi_client.models.select_options_input_feedback_dto.SelectOptionsInputFeedbackDto(
                    correct_option_ids = [
                        ''
                        ], 
                    incorrect_option_ids = [
                        ''
                        ], 
                    is_retype_answer_enabled = True, )
            )
        else:
            return ExerciseInputSelectOptionsDto(
        )
        """

    def testExerciseInputSelectOptionsDto(self):
        """Test ExerciseInputSelectOptionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
