# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update1_request import Update1Request

class TestUpdate1Request(unittest.TestCase):
    """Update1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Update1Request:
        """Test Update1Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Update1Request`
        """
        model = Update1Request()
        if include_optional:
            return Update1Request(
                flashcard = openapi_client.models.flashcard_dto.FlashcardDto(
                    id = '', 
                    deck_id = '', 
                    deck_order = 56, 
                    front_content = null, 
                    back_content = null, ),
                files = [
                    bytes(b'blah')
                    ]
            )
        else:
            return Update1Request(
                flashcard = openapi_client.models.flashcard_dto.FlashcardDto(
                    id = '', 
                    deck_id = '', 
                    deck_order = 56, 
                    front_content = null, 
                    back_content = null, ),
        )
        """

    def testUpdate1Request(self):
        """Test Update1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
