# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flashcard_content_upload_audio_dto import FlashcardContentUploadAudioDto

class TestFlashcardContentUploadAudioDto(unittest.TestCase):
    """FlashcardContentUploadAudioDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlashcardContentUploadAudioDto:
        """Test FlashcardContentUploadAudioDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlashcardContentUploadAudioDto`
        """
        model = FlashcardContentUploadAudioDto()
        if include_optional:
            return FlashcardContentUploadAudioDto(
                audio_file_name = '',
                language_id = ''
            )
        else:
            return FlashcardContentUploadAudioDto(
        )
        """

    def testFlashcardContentUploadAudioDto(self):
        """Test FlashcardContentUploadAudioDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
