# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.submit_answer_rich_request import SubmitAnswerRichRequest

class TestSubmitAnswerRichRequest(unittest.TestCase):
    """SubmitAnswerRichRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitAnswerRichRequest:
        """Test SubmitAnswerRichRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitAnswerRichRequest`
        """
        model = SubmitAnswerRichRequest()
        if include_optional:
            return SubmitAnswerRichRequest(
                answer = None,
                files = [
                    bytes(b'blah')
                    ]
            )
        else:
            return SubmitAnswerRichRequest(
                answer = None,
        )
        """

    def testSubmitAnswerRichRequest(self):
        """Test SubmitAnswerRichRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
