# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_pair_options_dto import ExerciseInputPairOptionsDto

class TestExerciseInputPairOptionsDto(unittest.TestCase):
    """ExerciseInputPairOptionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputPairOptionsDto:
        """Test ExerciseInputPairOptionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputPairOptionsDto`
        """
        model = ExerciseInputPairOptionsDto()
        if include_optional:
            return ExerciseInputPairOptionsDto(
                left_option_type = '',
                right_option_type = '',
                left_options = [
                    openapi_client.models.pair_options_input_option_dto.PairOptionsInputOptionDto(
                        id = '', )
                    ],
                right_options = [
                    openapi_client.models.pair_options_input_option_dto.PairOptionsInputOptionDto(
                        id = '', )
                    ],
                feedback = openapi_client.models.pair_options_input_feedback.PairOptionsInputFeedback(
                    correct_pairs = [
                        openapi_client.models.pair_option_feedback_pair.PairOptionFeedbackPair(
                            left_id = '', 
                            right_id = '', )
                        ], 
                    incorrect_pairs = [
                        openapi_client.models.pair_option_feedback_pair.PairOptionFeedbackPair(
                            left_id = '', 
                            right_id = '', )
                        ], )
            )
        else:
            return ExerciseInputPairOptionsDto(
                left_option_type = '',
                right_option_type = '',
                left_options = [
                    openapi_client.models.pair_options_input_option_dto.PairOptionsInputOptionDto(
                        id = '', )
                    ],
                right_options = [
                    openapi_client.models.pair_options_input_option_dto.PairOptionsInputOptionDto(
                        id = '', )
                    ],
        )
        """

    def testExerciseInputPairOptionsDto(self):
        """Test ExerciseInputPairOptionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
