# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_select_placeholders_dto import ExerciseInputSelectPlaceholdersDto

class TestExerciseInputSelectPlaceholdersDto(unittest.TestCase):
    """ExerciseInputSelectPlaceholdersDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputSelectPlaceholdersDto:
        """Test ExerciseInputSelectPlaceholdersDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputSelectPlaceholdersDto`
        """
        model = ExerciseInputSelectPlaceholdersDto()
        if include_optional:
            return ExerciseInputSelectPlaceholdersDto(
                parts = [
                    openapi_client.models.select_placeholders_input_part.SelectPlaceholdersInputPart(
                        type = '', 
                        value = '', )
                    ],
                options = [
                    openapi_client.models.select_placeholders_input_option.SelectPlaceholdersInputOption(
                        id = '', 
                        text = '', )
                    ]
            )
        else:
            return ExerciseInputSelectPlaceholdersDto(
                parts = [
                    openapi_client.models.select_placeholders_input_part.SelectPlaceholdersInputPart(
                        type = '', 
                        value = '', )
                    ],
                options = [
                    openapi_client.models.select_placeholders_input_option.SelectPlaceholdersInputOption(
                        id = '', 
                        text = '', )
                    ],
        )
        """

    def testExerciseInputSelectPlaceholdersDto(self):
        """Test ExerciseInputSelectPlaceholdersDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
