# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_feedback_text_dto import ExerciseInputFeedbackTextDto

class TestExerciseInputFeedbackTextDto(unittest.TestCase):
    """ExerciseInputFeedbackTextDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputFeedbackTextDto:
        """Test ExerciseInputFeedbackTextDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputFeedbackTextDto`
        """
        model = ExerciseInputFeedbackTextDto()
        if include_optional:
            return ExerciseInputFeedbackTextDto(
                correct_values = [
                    ''
                    ],
                incorrect_values = [
                    ''
                    ],
                is_retype_answer_enabled = True
            )
        else:
            return ExerciseInputFeedbackTextDto(
                correct_values = [
                    ''
                    ],
                incorrect_values = [
                    ''
                    ],
        )
        """

    def testExerciseInputFeedbackTextDto(self):
        """Test ExerciseInputFeedbackTextDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
