# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flashcard_content_upload_image_dto import FlashcardContentUploadImageDto

class TestFlashcardContentUploadImageDto(unittest.TestCase):
    """FlashcardContentUploadImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlashcardContentUploadImageDto:
        """Test FlashcardContentUploadImageDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlashcardContentUploadImageDto`
        """
        model = FlashcardContentUploadImageDto()
        if include_optional:
            return FlashcardContentUploadImageDto(
                image_file_name = ''
            )
        else:
            return FlashcardContentUploadImageDto(
        )
        """

    def testFlashcardContentUploadImageDto(self):
        """Test FlashcardContentUploadImageDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
