# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_select_review_options_dto import ExerciseInputSelectReviewOptionsDto

class TestExerciseInputSelectReviewOptionsDto(unittest.TestCase):
    """ExerciseInputSelectReviewOptionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputSelectReviewOptionsDto:
        """Test ExerciseInputSelectReviewOptionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputSelectReviewOptionsDto`
        """
        model = ExerciseInputSelectReviewOptionsDto()
        if include_optional:
            return ExerciseInputSelectReviewOptionsDto(
                rating = ''
            )
        else:
            return ExerciseInputSelectReviewOptionsDto(
                rating = '',
        )
        """

    def testExerciseInputSelectReviewOptionsDto(self):
        """Test ExerciseInputSelectReviewOptionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
