# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.exercise_session_controller_api import ExerciseSessionControllerApi


class TestExerciseSessionControllerApi(unittest.TestCase):
    """ExerciseSessionControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExerciseSessionControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create2(self) -> None:
        """Test case for create2

        """
        pass

    def test_get5(self) -> None:
        """Test case for get5

        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        """
        pass

    def test_next_exercise(self) -> None:
        """Test case for next_exercise

        """
        pass

    def test_skip_exercise(self) -> None:
        """Test case for skip_exercise

        """
        pass

    def test_update_config(self) -> None:
        """Test case for update_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
