# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.configuration_identifier_dto import ConfigurationIdentifierDto

class TestConfigurationIdentifierDto(unittest.TestCase):
    """ConfigurationIdentifierDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationIdentifierDto:
        """Test ConfigurationIdentifierDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigurationIdentifierDto`
        """
        model = ConfigurationIdentifierDto()
        if include_optional:
            return ConfigurationIdentifierDto(
                id = '',
                type = ''
            )
        else:
            return ConfigurationIdentifierDto(
        )
        """

    def testConfigurationIdentifierDto(self):
        """Test ConfigurationIdentifierDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
