# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_session_options_select_flashcards_dto import ExerciseSessionOptionsSelectFlashcardsDto

class TestExerciseSessionOptionsSelectFlashcardsDto(unittest.TestCase):
    """ExerciseSessionOptionsSelectFlashcardsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseSessionOptionsSelectFlashcardsDto:
        """Test ExerciseSessionOptionsSelectFlashcardsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseSessionOptionsSelectFlashcardsDto`
        """
        model = ExerciseSessionOptionsSelectFlashcardsDto()
        if include_optional:
            return ExerciseSessionOptionsSelectFlashcardsDto(
                initial_flashcard_language_id = '',
                available_flashcard_languages = [
                    openapi_client.models.exercise_session_options_language_option_dto.ExerciseSessionOptionsLanguageOptionDto(
                        id = '', 
                        iso_code = '', )
                    ]
            )
        else:
            return ExerciseSessionOptionsSelectFlashcardsDto(
        )
        """

    def testExerciseSessionOptionsSelectFlashcardsDto(self):
        """Test ExerciseSessionOptionsSelectFlashcardsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
