# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_input_write_text_dto import ExerciseInputWriteTextDto

class TestExerciseInputWriteTextDto(unittest.TestCase):
    """ExerciseInputWriteTextDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseInputWriteTextDto:
        """Test ExerciseInputWriteTextDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseInputWriteTextDto`
        """
        model = ExerciseInputWriteTextDto()
        if include_optional:
            return ExerciseInputWriteTextDto(
                text = '',
                feedback = openapi_client.models.exercise_input_feedback_text_dto.ExerciseInputFeedbackTextDto(
                    correct_values = [
                        ''
                        ], 
                    incorrect_values = [
                        ''
                        ], 
                    is_retype_answer_enabled = True, )
            )
        else:
            return ExerciseInputWriteTextDto(
                text = '',
        )
        """

    def testExerciseInputWriteTextDto(self):
        """Test ExerciseInputWriteTextDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
