# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.root_controller_api import RootControllerApi


class TestRootControllerApi(unittest.TestCase):
    """RootControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RootControllerApi()

    def tearDown(self) -> None:
        pass

    def test_ping(self) -> None:
        """Test case for ping

        """
        pass

    def test_reset_graph(self) -> None:
        """Test case for reset_graph

        """
        pass


if __name__ == '__main__':
    unittest.main()
