# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flashcard_language_dto import FlashcardLanguageDto

class TestFlashcardLanguageDto(unittest.TestCase):
    """FlashcardLanguageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlashcardLanguageDto:
        """Test FlashcardLanguageDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlashcardLanguageDto`
        """
        model = FlashcardLanguageDto()
        if include_optional:
            return FlashcardLanguageDto(
                id = '',
                abbreviation = '',
                name = ''
            )
        else:
            return FlashcardLanguageDto(
        )
        """

    def testFlashcardLanguageDto(self):
        """Test FlashcardLanguageDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
