# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exercise_dto import ExerciseDto

class TestExerciseDto(unittest.TestCase):
    """ExerciseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExerciseDto:
        """Test ExerciseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExerciseDto`
        """
        model = ExerciseDto()
        if include_optional:
            return ExerciseDto(
                id = '',
                type = '',
                content = None,
                input = None,
                feedback = openapi_client.models.exercise_feedback_dto.ExerciseFeedbackDto(
                    type = '', 
                    state = '', 
                    message = '', ),
                properties = openapi_client.models.exercise_dto_properties.ExerciseDto_properties(
                    empty = True, )
            )
        else:
            return ExerciseDto(
                id = '',
                type = '',
        )
        """

    def testExerciseDto(self):
        """Test ExerciseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
