/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDto } from './configuration-dto';


export interface ConfigurationGoogleSpeechToTextDto extends ConfigurationDto { 
    languageCode?: string;
}

