/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationGoogleTranslateDto } from './configuration-google-translate-dto';
import { ConfigurationDto } from './configuration-dto';
import { ConfigurationMicrosoftTextToSpeechDto } from './configuration-microsoft-text-to-speech-dto';
import { ConfigurationGoogleSpeechToTextDto } from './configuration-google-speech-to-text-dto';
import { ConfigurationGoogleTextToSpeechDto } from './configuration-google-text-to-speech-dto';


/**
 * @type CreateConfigRequest
 * @export
 */
export type CreateConfigRequest = ConfigurationDto | ConfigurationGoogleSpeechToTextDto | ConfigurationGoogleTextToSpeechDto | ConfigurationGoogleTranslateDto | ConfigurationMicrosoftTextToSpeechDto;

