/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseSessionOptionsDto } from './exercise-session-options-dto';


export interface ExerciseSessionOptionsReviewFlashcardsDto extends ExerciseSessionOptionsDto { 
    initialFlashcardLanguageId?: string;
    availableFlashcardLanguageIds?: Array<string>;
}

