/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseSessionOptionsDto } from './exercise-session-options-dto';
import { ExerciseSessionOptionsLanguageOptionDto } from './exercise-session-options-language-option-dto';


export interface ExerciseSessionOptionsWriteFlashcardsDto extends ExerciseSessionOptionsDto { 
    answerLanguageId?: string;
    availableAnswerLanguages?: Array<ExerciseSessionOptionsLanguageOptionDto>;
    retypeCorrectAnswerEnabled?: boolean;
}

