/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseContentVideoDto } from './exercise-content-video-dto';
import { ExerciseContentTextDto } from './exercise-content-text-dto';
import { ExerciseContentFlashcardDto } from './exercise-content-flashcard-dto';
import { ExerciseContentAudioDto } from './exercise-content-audio-dto';
import { ExerciseContentDto } from './exercise-content-dto';
import { ExerciseContentFlashcardSideDto } from './exercise-content-flashcard-side-dto';
import { ExerciseContentImageDto } from './exercise-content-image-dto';


/**
 * @type ExerciseDtoContent
 * @export
 */
export type ExerciseDtoContent = ExerciseContentAudioDto | ExerciseContentFlashcardDto | ExerciseContentFlashcardSideDto | ExerciseContentImageDto | ExerciseContentTextDto | ExerciseContentVideoDto;

