/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseInputDto } from './exercise-input-dto';
import { ExerciseInputFeedbackMultipleChoiceTextFeedbackDto } from './exercise-input-feedback-multiple-choice-text-feedback-dto';
import { Option } from './option';


export interface ExerciseInputMultipleChoiceTextDto extends ExerciseInputDto { 
    feedback?: ExerciseInputFeedbackMultipleChoiceTextFeedbackDto;
    options?: Array<Option>;
    value?: string;
}

