/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseContentDto } from './exercise-content-dto';


export interface ExerciseContentImageDto extends ExerciseContentDto { 
    imageUrl?: string;
}

