/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExerciseSessionProgressDto { 
    type?: string;
    percentage?: number;
    currentBatch?: number;
    hasMoreBatches?: boolean;
    reviewNewPercentage?: number;
    reviewLearningPercentage?: number;
    reviewLongTermPercentage?: number;
}

