/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlashcardContentVideoDto } from './flashcard-content-video-dto';
import { FlashcardContentUploadImageDto } from './flashcard-content-upload-image-dto';
import { FlashcardContentTextDto } from './flashcard-content-text-dto';
import { FlashcardContentUploadVideoDto } from './flashcard-content-upload-video-dto';
import { FlashcardContentUploadAudioDto } from './flashcard-content-upload-audio-dto';
import { FlashcardContentAudioDto } from './flashcard-content-audio-dto';
import { FlashcardContentDto } from './flashcard-content-dto';
import { FlashcardContentImageDto } from './flashcard-content-image-dto';


/**
 * @type FlashcardDtoFrontContent
 * @export
 */
export type FlashcardDtoFrontContent = FlashcardContentAudioDto | FlashcardContentDto | FlashcardContentImageDto | FlashcardContentTextDto | FlashcardContentUploadAudioDto | FlashcardContentUploadImageDto | FlashcardContentUploadVideoDto | FlashcardContentVideoDto;

