/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlashcardDtoFrontContent } from './flashcard-dto-front-content';


export interface FlashcardDto { 
    id: string;
    deckId?: string;
    deckOrder?: number;
    frontContent?: FlashcardDtoFrontContent;
    backContent?: FlashcardDtoFrontContent;
}

