/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PairOptionFeedbackPair } from './pair-option-feedback-pair';


export interface PairOptionsInputFeedback { 
    correctPairs: Array<PairOptionFeedbackPair>;
    incorrectPairs: Array<PairOptionFeedbackPair>;
}

