/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SelectOptionInputTextOption { 
    id: string;
    text: string;
}

export interface SelectOptionInputAudioOption {
    id: string;
    url: string;
}

export interface SelectOptionInputImageOption {
    id: string;
    url: string;
}

export interface SelectOptionInputVideoOption {
    id: string;
    url: string;
}

export type SelectOptionInputOption = SelectOptionInputTextOption | SelectOptionInputAudioOption | SelectOptionInputImageOption | SelectOptionInputVideoOption;  