/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmitAnswerRequest } from './submit-answer-request';


export interface SubmitAnswerRichRequest { 
    answer: SubmitAnswerRequest;
    files?: Array<Blob>;
}

