/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PairOptionsInputOptionDto } from './pair-options-input-option-dto';
import { ExerciseInputFeedbackTextDto } from './exercise-input-feedback-text-dto';
import { ExerciseInputSelectOptionsDto } from './exercise-input-select-options-dto';
import { ExerciseInputRecordAudioDto } from './exercise-input-record-audio-dto';
import { ExerciseInputDto } from './exercise-input-dto';
import { ExerciseInputPairOptionsDto } from './exercise-input-pair-options-dto';
import { ExerciseInputArrangeTextOptionsDto } from './exercise-input-arrange-text-options-dto';
import { WritePlaceholdersPartDto } from './write-placeholders-part-dto';
import { ExerciseInputSelectReviewOptionsDto } from './exercise-input-select-review-options-dto';
import { ExerciseInputSelectPlaceholdersDto } from './exercise-input-select-placeholders-dto';
import { SelectPlaceholdersInputOption } from './select-placeholders-input-option';
import { ExerciseInputRecordVideoDto } from './exercise-input-record-video-dto';
import { ExerciseInputWritePlaceholdersDto } from './exercise-input-write-placeholders-dto';
import { ExerciseInputWriteTextDto } from './exercise-input-write-text-dto';


/**
 * @type SubmitAnswerRequest
 * @export
 */
export type SubmitAnswerRequest = ExerciseInputArrangeTextOptionsDto | ExerciseInputDto | ExerciseInputPairOptionsDto | ExerciseInputRecordAudioDto | ExerciseInputRecordVideoDto | ExerciseInputSelectOptionsDto | ExerciseInputSelectPlaceholdersDto | ExerciseInputSelectReviewOptionsDto | ExerciseInputWritePlaceholdersDto | ExerciseInputWriteTextDto;

