/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExerciseSessionOptionsSelectFlashcardsDto } from './exercise-session-options-select-flashcards-dto';
import { ExerciseSessionOptionsLearnFlashcardsDto } from './exercise-session-options-learn-flashcards-dto';
import { ExerciseSessionOptionsReviewFlashcardsDto } from './exercise-session-options-review-flashcards-dto';
import { ExerciseSessionOptionsWriteFlashcardsDto } from './exercise-session-options-write-flashcards-dto';
import { ExerciseSessionOptionsLanguageOptionDto } from './exercise-session-options-language-option-dto';


/**
 * @type UpdateConfigRequest
 * @export
 */
export type UpdateConfigRequest = ExerciseSessionOptionsLearnFlashcardsDto | ExerciseSessionOptionsReviewFlashcardsDto | ExerciseSessionOptionsSelectFlashcardsDto | ExerciseSessionOptionsWriteFlashcardsDto;

