/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlashcardDto } from './flashcard-dto';


export interface Update1Request { 
    flashcard: FlashcardDto;
    files?: Array<Blob>;
}

