/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VocabularyContentTextDto } from './vocabulary-content-text-dto';


export interface VocabularyDto { 
    words?: Array<VocabularyContentTextDto>;
}

