name: diy-birdy-app

# Services: Backend API (Spring Boot)
services:
- name: backend 
  source_dir: api
  dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: Explik/diybirdyapp
  
# Workers: Gremlin Graph Database Server
workers:
  - name: gremlin-server
    image:
      registry_type: DOCKER_HUB
      repository: tinkerpop/gremlin-server
      tag: "3.7.0"
    
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    
    # Environment variables for Gremlin
    envs:
      - key: GREMLIN_SERVER_USER
        value: gremlin
        scope: RUN_TIME
        type: general
      - key: GREMLIN_SERVER_PASSWORD
        value: gremlin
        scope: RUN_TIME
        type: secret