name: diy-birdy-app

# Services: Backend API (Spring Boot)
services:
- name: backend 
  source_dir: api
  dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: Explik/diybirdyapp
  