export * from './authentication-controller.service';
import { AuthenticationControllerService } from './authentication-controller.service';
export * from './authentication-controller.serviceInterface';
export * from './configuration-controller.service';
import { ConfigurationControllerService } from './configuration-controller.service';
export * from './configuration-controller.serviceInterface';
export * from './exercise-controller.service';
import { ExerciseControllerService } from './exercise-controller.service';
export * from './exercise-controller.serviceInterface';
export * from './exercise-session-controller.service';
import { ExerciseSessionControllerService } from './exercise-session-controller.service';
export * from './exercise-session-controller.serviceInterface';
export * from './file-controller.service';
import { FileControllerService } from './file-controller.service';
export * from './file-controller.serviceInterface';
export * from './flashcard-controller.service';
import { FlashcardControllerService } from './flashcard-controller.service';
export * from './flashcard-controller.serviceInterface';
export * from './flashcard-deck-controller.service';
import { FlashcardDeckControllerService } from './flashcard-deck-controller.service';
export * from './flashcard-deck-controller.serviceInterface';
export * from './language-controller.service';
import { LanguageControllerService } from './language-controller.service';
export * from './language-controller.serviceInterface';
export * from './root-controller.service';
import { RootControllerService } from './root-controller.service';
export * from './root-controller.serviceInterface';
export * from './text-content-controller.service';
import { TextContentControllerService } from './text-content-controller.service';
export * from './text-content-controller.serviceInterface';
export * from './vocabulary-controller.service';
import { VocabularyControllerService } from './vocabulary-controller.service';
export * from './vocabulary-controller.serviceInterface';
export const APIS = [AuthenticationControllerService, ConfigurationControllerService, ExerciseControllerService, ExerciseSessionControllerService, FileControllerService, FlashcardControllerService, FlashcardDeckControllerService, LanguageControllerService, RootControllerService, TextContentControllerService, VocabularyControllerService];
