/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginDto } from '../model/models';
import { SignupDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param loginDto 
     */
    login(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param signupDto 
     */
    registerUser(signupDto: SignupDto, extraHttpRequestParams?: any): Observable<object>;

}
