/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConfigurationDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConfigurationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param languageId 
     */
    getAll3(languageId: string, extraHttpRequestParams?: any): Observable<Array<ConfigurationDto>>;

}
