/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExerciseDto } from '../model/models';
import { ExerciseInputArrangeTextOptionsDto } from '../model/models';
import { ExerciseInputDto } from '../model/models';
import { ExerciseInputPairOptionsDto } from '../model/models';
import { ExerciseInputRecordAudioDto } from '../model/models';
import { ExerciseInputRecordVideoDto } from '../model/models';
import { ExerciseInputSelectOptionsDto } from '../model/models';
import { ExerciseInputSelectPlaceholdersDto } from '../model/models';
import { ExerciseInputSelectReviewOptionsDto } from '../model/models';
import { ExerciseInputWritePlaceholdersDto } from '../model/models';
import { ExerciseInputWriteTextDto } from '../model/models';
import { SubmitAnswerRequest } from '../model/models';
import { SubmitAnswerRichRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExerciseControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    get3(extraHttpRequestParams?: any): Observable<Array<ExerciseDto>>;

    /**
     * 
     * 
     * @param id 
     * @param sessionId 
     */
    get4(id: string, sessionId?: string, extraHttpRequestParams?: any): Observable<ExerciseDto>;

    /**
     * 
     * 
     */
    getTypes(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * 
     * 
     * @param id 
     * @param exerciseInputDtoExerciseInputArrangeTextOptionsDtoExerciseInputPairOptionsDtoExerciseInputRecordAudioDtoExerciseInputRecordVideoDtoExerciseInputSelectOptionsDtoExerciseInputSelectPlaceholdersDtoExerciseInputSelectReviewOptionsDtoExerciseInputWritePlaceholdersDtoExerciseInputWriteTextDto 
     */
    submitAnswer(id: string, exerciseInputDtoExerciseInputArrangeTextOptionsDtoExerciseInputPairOptionsDtoExerciseInputRecordAudioDtoExerciseInputRecordVideoDtoExerciseInputSelectOptionsDtoExerciseInputSelectPlaceholdersDtoExerciseInputSelectReviewOptionsDtoExerciseInputWritePlaceholdersDtoExerciseInputWriteTextDto: ExerciseInputDto | ExerciseInputArrangeTextOptionsDto | ExerciseInputPairOptionsDto | ExerciseInputRecordAudioDto | ExerciseInputRecordVideoDto | ExerciseInputSelectOptionsDto | ExerciseInputSelectPlaceholdersDto | ExerciseInputSelectReviewOptionsDto | ExerciseInputWritePlaceholdersDto | ExerciseInputWriteTextDto, extraHttpRequestParams?: any): Observable<ExerciseDto>;

    /**
     * 
     * 
     * @param id 
     * @param submitAnswerRichRequest 
     */
    submitAnswerRich(id: string, submitAnswerRichRequest?: SubmitAnswerRichRequest, extraHttpRequestParams?: any): Observable<ExerciseDto>;

}
