/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExerciseSessionDto } from '../model/models';
import { ExerciseSessionOptionsLearnFlashcardsDto } from '../model/models';
import { ExerciseSessionOptionsReviewFlashcardsDto } from '../model/models';
import { ExerciseSessionOptionsSelectFlashcardsDto } from '../model/models';
import { ExerciseSessionOptionsWriteFlashcardsDto } from '../model/models';
import { UpdateConfigRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExerciseSessionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param exerciseSessionDto 
     */
    create2(exerciseSessionDto: ExerciseSessionDto, extraHttpRequestParams?: any): Observable<ExerciseSessionDto>;

    /**
     * 
     * 
     * @param id 
     */
    get5(id: string, extraHttpRequestParams?: any): Observable<ExerciseSessionDto>;

    /**
     * 
     * 
     * @param id 
     */
    getConfig(id: string, extraHttpRequestParams?: any): Observable<UpdateConfigRequest>;

    /**
     * 
     * 
     * @param id 
     */
    nextExercise(id: string, extraHttpRequestParams?: any): Observable<ExerciseSessionDto>;

    /**
     * 
     * 
     * @param id 
     */
    skipExercise(id: string, extraHttpRequestParams?: any): Observable<ExerciseSessionDto>;

    /**
     * 
     * 
     * @param id 
     * @param exerciseSessionOptionsLearnFlashcardsDtoExerciseSessionOptionsReviewFlashcardsDtoExerciseSessionOptionsSelectFlashcardsDtoExerciseSessionOptionsWriteFlashcardsDto 
     */
    updateConfig(id: string, exerciseSessionOptionsLearnFlashcardsDtoExerciseSessionOptionsReviewFlashcardsDtoExerciseSessionOptionsSelectFlashcardsDtoExerciseSessionOptionsWriteFlashcardsDto: ExerciseSessionOptionsLearnFlashcardsDto | ExerciseSessionOptionsReviewFlashcardsDto | ExerciseSessionOptionsSelectFlashcardsDto | ExerciseSessionOptionsWriteFlashcardsDto, extraHttpRequestParams?: any): Observable<ExerciseSessionDto>;

}
