/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FlashcardDto } from '../model/models';
import { Update1Request } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FlashcardControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param flashcardDto 
     */
    create(flashcardDto: FlashcardDto, extraHttpRequestParams?: any): Observable<FlashcardDto>;

    /**
     * 
     * 
     * @param update1Request 
     */
    createRich(update1Request?: Update1Request, extraHttpRequestParams?: any): Observable<FlashcardDto>;

    /**
     * 
     * 
     * @param id 
     */
    get1(id: string, extraHttpRequestParams?: any): Observable<FlashcardDto>;

    /**
     * 
     * 
     * @param deckId 
     */
    getAll1(deckId?: string, extraHttpRequestParams?: any): Observable<Array<FlashcardDto>>;

    /**
     * 
     * 
     * @param flashcardDto 
     */
    update(flashcardDto: FlashcardDto, extraHttpRequestParams?: any): Observable<FlashcardDto>;

    /**
     * 
     * 
     * @param update1Request 
     */
    update1(update1Request?: Update1Request, extraHttpRequestParams?: any): Observable<FlashcardDto>;

}
