/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FlashcardLanguageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LanguageControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<FlashcardLanguageDto>>;

}
