/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TextContentTranscriptionDto } from '../model/models';
import { UploadFileRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TextContentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     * @param textContentTranscriptionDto 
     */
    addTranscription(id: string, textContentTranscriptionDto: TextContentTranscriptionDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getPronunciation(id: string, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * 
     * 
     * @param id 
     * @param uploadFileRequest 
     */
    uploadPronunciation(id: string, uploadFileRequest?: UploadFileRequest, extraHttpRequestParams?: any): Observable<{}>;

}
