# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.option import Option
from typing import Optional, Set
from typing_extensions import Self

class ConfigurationOptionsDto(BaseModel):
    """
    ConfigurationOptionsDto
    """ # noqa: E501
    selection: Optional[StrictStr] = None
    selected_options: Optional[List[StrictStr]] = Field(default=None, alias="selectedOptions")
    available_options: Optional[List[Option]] = Field(default=None, alias="availableOptions")
    last_selection: Optional[StrictBool] = Field(default=None, alias="lastSelection")
    __properties: ClassVar[List[str]] = ["selection", "selectedOptions", "availableOptions", "lastSelection"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigurationOptionsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_options (list)
        _items = []
        if self.available_options:
            for _item_available_options in self.available_options:
                if _item_available_options:
                    _items.append(_item_available_options.to_dict())
            _dict['availableOptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigurationOptionsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "selection": obj.get("selection"),
            "selectedOptions": obj.get("selectedOptions"),
            "availableOptions": [Option.from_dict(_item) for _item in obj["availableOptions"]] if obj.get("availableOptions") is not None else None,
            "lastSelection": obj.get("lastSelection")
        })
        return _obj


