# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.exercise_session_options_dto import ExerciseSessionOptionsDto
from openapi_client.models.exercise_session_options_language_option_dto import ExerciseSessionOptionsLanguageOptionDto
from typing import Optional, Set
from typing_extensions import Self

class ExerciseSessionOptionsWriteFlashcardsDto(ExerciseSessionOptionsDto):
    """
    ExerciseSessionOptionsWriteFlashcardsDto
    """ # noqa: E501
    answer_language_id: Optional[StrictStr] = Field(default=None, alias="answerLanguageId")
    available_answer_languages: Optional[List[ExerciseSessionOptionsLanguageOptionDto]] = Field(default=None, alias="availableAnswerLanguages")
    retype_correct_answer_enabled: Optional[StrictBool] = Field(default=None, alias="retypeCorrectAnswerEnabled")
    __properties: ClassVar[List[str]] = ["type", "textToSpeechEnabled", "answerLanguageId", "availableAnswerLanguages", "retypeCorrectAnswerEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseSessionOptionsWriteFlashcardsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_answer_languages (list)
        _items = []
        if self.available_answer_languages:
            for _item_available_answer_languages in self.available_answer_languages:
                if _item_available_answer_languages:
                    _items.append(_item_available_answer_languages.to_dict())
            _dict['availableAnswerLanguages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseSessionOptionsWriteFlashcardsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "textToSpeechEnabled": obj.get("textToSpeechEnabled"),
            "answerLanguageId": obj.get("answerLanguageId"),
            "availableAnswerLanguages": [ExerciseSessionOptionsLanguageOptionDto.from_dict(_item) for _item in obj["availableAnswerLanguages"]] if obj.get("availableAnswerLanguages") is not None else None,
            "retypeCorrectAnswerEnabled": obj.get("retypeCorrectAnswerEnabled")
        })
        return _obj


