# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openapi_client.models.exercise_session_options_learn_flashcards_dto import ExerciseSessionOptionsLearnFlashcardsDto
    from openapi_client.models.exercise_session_options_review_flashcards_dto import ExerciseSessionOptionsReviewFlashcardsDto
    from openapi_client.models.exercise_session_options_select_flashcards_dto import ExerciseSessionOptionsSelectFlashcardsDto
    from openapi_client.models.exercise_session_options_write_flashcards_dto import ExerciseSessionOptionsWriteFlashcardsDto

class ExerciseSessionOptionsDto(BaseModel):
    """
    ExerciseSessionOptionsDto
    """ # noqa: E501
    type: Optional[StrictStr] = None
    text_to_speech_enabled: Optional[StrictBool] = Field(default=None, alias="textToSpeechEnabled")
    __properties: ClassVar[List[str]] = ["type", "textToSpeechEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'ExerciseSessionOptionsLearnFlashcardsDto': 'ExerciseSessionOptionsLearnFlashcardsDto','ExerciseSessionOptionsReviewFlashcardsDto': 'ExerciseSessionOptionsReviewFlashcardsDto','ExerciseSessionOptionsSelectFlashcardsDto': 'ExerciseSessionOptionsSelectFlashcardsDto','ExerciseSessionOptionsWriteFlashcardsDto': 'ExerciseSessionOptionsWriteFlashcardsDto'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto]]:
        """Create an instance of ExerciseSessionOptionsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto]]:
        """Create an instance of ExerciseSessionOptionsDto from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'ExerciseSessionOptionsLearnFlashcardsDto':
            return import_module("openapi_client.models.exercise_session_options_learn_flashcards_dto").ExerciseSessionOptionsLearnFlashcardsDto.from_dict(obj)
        if object_type ==  'ExerciseSessionOptionsReviewFlashcardsDto':
            return import_module("openapi_client.models.exercise_session_options_review_flashcards_dto").ExerciseSessionOptionsReviewFlashcardsDto.from_dict(obj)
        if object_type ==  'ExerciseSessionOptionsSelectFlashcardsDto':
            return import_module("openapi_client.models.exercise_session_options_select_flashcards_dto").ExerciseSessionOptionsSelectFlashcardsDto.from_dict(obj)
        if object_type ==  'ExerciseSessionOptionsWriteFlashcardsDto':
            return import_module("openapi_client.models.exercise_session_options_write_flashcards_dto").ExerciseSessionOptionsWriteFlashcardsDto.from_dict(obj)

        raise ValueError("ExerciseSessionOptionsDto failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


