# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.exercise_content_dto import ExerciseContentDto
from typing import Optional, Set
from typing_extensions import Self

class ExerciseContentFlashcardDto(ExerciseContentDto):
    """
    ExerciseContentFlashcardDto
    """ # noqa: E501
    front: Optional[ExerciseContentDto] = None
    back: Optional[ExerciseContentDto] = None
    initial_side: Optional[StrictStr] = Field(default=None, alias="initialSide")
    __properties: ClassVar[List[str]] = ["id", "type", "front", "back", "initialSide"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseContentFlashcardDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of front
        if self.front:
            _dict['front'] = self.front.to_dict()
        # override the default output from pydantic by calling `to_dict()` of back
        if self.back:
            _dict['back'] = self.back.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseContentFlashcardDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "front": ExerciseContentDto.from_dict(obj["front"]) if obj.get("front") is not None else None,
            "back": ExerciseContentDto.from_dict(obj["back"]) if obj.get("back") is not None else None,
            "initialSide": obj.get("initialSide")
        })
        return _obj


