# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .exercise_input_dto import ExerciseInputDto
from .pair_options_input_feedback import PairOptionsInputFeedback
from .pair_options_input_option_dto import PairOptionsInputOptionDto
from typing import Optional, Set
from typing_extensions import Self

class ExerciseInputPairOptionsDto(ExerciseInputDto):
    """
    ExerciseInputPairOptionsDto
    """ # noqa: E501
    left_option_type: StrictStr = Field(alias="leftOptionType")
    right_option_type: StrictStr = Field(alias="rightOptionType")
    left_options: List[PairOptionsInputOptionDto] = Field(alias="leftOptions")
    right_options: List[PairOptionsInputOptionDto] = Field(alias="rightOptions")
    feedback: Optional[PairOptionsInputFeedback] = None
    __properties: ClassVar[List[str]] = ["id", "type", "sessionId", "leftOptionType", "rightOptionType", "leftOptions", "rightOptions", "feedback"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseInputPairOptionsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in left_options (list)
        _items = []
        if self.left_options:
            for _item_left_options in self.left_options:
                if _item_left_options:
                    _items.append(_item_left_options.to_dict())
            _dict['leftOptions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in right_options (list)
        _items = []
        if self.right_options:
            for _item_right_options in self.right_options:
                if _item_right_options:
                    _items.append(_item_right_options.to_dict())
            _dict['rightOptions'] = _items
        # override the default output from pydantic by calling `to_dict()` of feedback
        if self.feedback:
            _dict['feedback'] = self.feedback.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseInputPairOptionsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "sessionId": obj.get("sessionId"),
            "leftOptionType": obj.get("leftOptionType"),
            "rightOptionType": obj.get("rightOptionType"),
            "leftOptions": [PairOptionsInputOptionDto.from_dict(_item) for _item in obj["leftOptions"]] if obj.get("leftOptions") is not None else None,
            "rightOptions": [PairOptionsInputOptionDto.from_dict(_item) for _item in obj["rightOptions"]] if obj.get("rightOptions") is not None else None,
            "feedback": PairOptionsInputFeedback.from_dict(obj["feedback"]) if obj.get("feedback") is not None else None
        })
        return _obj


