# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .exercise_dto import ExerciseDto
from .exercise_session_progress_dto import ExerciseSessionProgressDto
from typing import Optional, Set
from typing_extensions import Self

class ExerciseSessionDto(BaseModel):
    """
    ExerciseSessionDto
    """ # noqa: E501
    id: Optional[StrictStr] = None
    type: StrictStr
    completed: Optional[StrictBool] = None
    flashcard_deck_id: Optional[StrictStr] = Field(default=None, alias="flashcardDeckId")
    exercise: Optional[ExerciseDto] = None
    progress: Optional[ExerciseSessionProgressDto] = None
    __properties: ClassVar[List[str]] = ["id", "type", "completed", "flashcardDeckId", "exercise", "progress"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseSessionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of exercise
        if self.exercise:
            _dict['exercise'] = self.exercise.to_dict()
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseSessionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "completed": obj.get("completed"),
            "flashcardDeckId": obj.get("flashcardDeckId"),
            "exercise": ExerciseDto.from_dict(obj["exercise"]) if obj.get("exercise") is not None else None,
            "progress": ExerciseSessionProgressDto.from_dict(obj["progress"]) if obj.get("progress") is not None else None
        })
        return _obj


