# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from .exercise_content_audio_dto import ExerciseContentAudioDto
from .exercise_content_flashcard_dto import ExerciseContentFlashcardDto
from .exercise_content_flashcard_side_dto import ExerciseContentFlashcardSideDto
from .exercise_content_image_dto import ExerciseContentImageDto
from .exercise_content_text_dto import ExerciseContentTextDto
from .exercise_content_video_dto import ExerciseContentVideoDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EXERCISEDTOCONTENT_ONE_OF_SCHEMAS = ["ExerciseContentAudioDto", "ExerciseContentFlashcardDto", "ExerciseContentFlashcardSideDto", "ExerciseContentImageDto", "ExerciseContentTextDto", "ExerciseContentVideoDto"]

class ExerciseDtoContent(BaseModel):
    """
    ExerciseDtoContent
    """
    # data type: ExerciseContentAudioDto
    oneof_schema_1_validator: Optional[ExerciseContentAudioDto] = None
    # data type: ExerciseContentFlashcardDto
    oneof_schema_2_validator: Optional[ExerciseContentFlashcardDto] = None
    # data type: ExerciseContentFlashcardSideDto
    oneof_schema_3_validator: Optional[ExerciseContentFlashcardSideDto] = None
    # data type: ExerciseContentImageDto
    oneof_schema_4_validator: Optional[ExerciseContentImageDto] = None
    # data type: ExerciseContentTextDto
    oneof_schema_5_validator: Optional[ExerciseContentTextDto] = None
    # data type: ExerciseContentVideoDto
    oneof_schema_6_validator: Optional[ExerciseContentVideoDto] = None
    actual_instance: Optional[Union[ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto]] = None
    one_of_schemas: Set[str] = { "ExerciseContentAudioDto", "ExerciseContentFlashcardDto", "ExerciseContentFlashcardSideDto", "ExerciseContentImageDto", "ExerciseContentTextDto", "ExerciseContentVideoDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ExerciseDtoContent.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExerciseContentAudioDto
        if not isinstance(v, ExerciseContentAudioDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentAudioDto`")
        else:
            match += 1
        # validate data type: ExerciseContentFlashcardDto
        if not isinstance(v, ExerciseContentFlashcardDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentFlashcardDto`")
        else:
            match += 1
        # validate data type: ExerciseContentFlashcardSideDto
        if not isinstance(v, ExerciseContentFlashcardSideDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentFlashcardSideDto`")
        else:
            match += 1
        # validate data type: ExerciseContentImageDto
        if not isinstance(v, ExerciseContentImageDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentImageDto`")
        else:
            match += 1
        # validate data type: ExerciseContentTextDto
        if not isinstance(v, ExerciseContentTextDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentTextDto`")
        else:
            match += 1
        # validate data type: ExerciseContentVideoDto
        if not isinstance(v, ExerciseContentVideoDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseContentVideoDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ExerciseDtoContent with oneOf schemas: ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ExerciseDtoContent with oneOf schemas: ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ExerciseContentAudioDto
        try:
            instance.actual_instance = ExerciseContentAudioDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseContentFlashcardDto
        try:
            instance.actual_instance = ExerciseContentFlashcardDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseContentFlashcardSideDto
        try:
            instance.actual_instance = ExerciseContentFlashcardSideDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseContentImageDto
        try:
            instance.actual_instance = ExerciseContentImageDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseContentTextDto
        try:
            instance.actual_instance = ExerciseContentTextDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseContentVideoDto
        try:
            instance.actual_instance = ExerciseContentVideoDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ExerciseDtoContent with oneOf schemas: ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ExerciseDtoContent with oneOf schemas: ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


