# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openapi_client.models.exercise_content_audio_dto import ExerciseContentAudioDto
    from openapi_client.models.exercise_content_flashcard_dto import ExerciseContentFlashcardDto
    from openapi_client.models.exercise_content_flashcard_side_dto import ExerciseContentFlashcardSideDto
    from openapi_client.models.exercise_content_image_dto import ExerciseContentImageDto
    from openapi_client.models.exercise_content_text_dto import ExerciseContentTextDto
    from openapi_client.models.exercise_content_video_dto import ExerciseContentVideoDto

class ExerciseContentDto(BaseModel):
    """
    ExerciseContentDto
    """ # noqa: E501
    id: StrictStr
    type: StrictStr
    __properties: ClassVar[List[str]] = ["id", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'ExerciseContentAudioDto': 'ExerciseContentAudioDto','ExerciseContentFlashcardDto': 'ExerciseContentFlashcardDto','ExerciseContentFlashcardSideDto': 'ExerciseContentFlashcardSideDto','ExerciseContentImageDto': 'ExerciseContentImageDto','ExerciseContentTextDto': 'ExerciseContentTextDto','ExerciseContentVideoDto': 'ExerciseContentVideoDto'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto]]:
        """Create an instance of ExerciseContentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[ExerciseContentAudioDto, ExerciseContentFlashcardDto, ExerciseContentFlashcardSideDto, ExerciseContentImageDto, ExerciseContentTextDto, ExerciseContentVideoDto]]:
        """Create an instance of ExerciseContentDto from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'ExerciseContentAudioDto':
            return import_module("openapi_client.models.exercise_content_audio_dto").ExerciseContentAudioDto.from_dict(obj)
        if object_type ==  'ExerciseContentFlashcardDto':
            return import_module("openapi_client.models.exercise_content_flashcard_dto").ExerciseContentFlashcardDto.from_dict(obj)
        if object_type ==  'ExerciseContentFlashcardSideDto':
            return import_module("openapi_client.models.exercise_content_flashcard_side_dto").ExerciseContentFlashcardSideDto.from_dict(obj)
        if object_type ==  'ExerciseContentImageDto':
            return import_module("openapi_client.models.exercise_content_image_dto").ExerciseContentImageDto.from_dict(obj)
        if object_type ==  'ExerciseContentTextDto':
            return import_module("openapi_client.models.exercise_content_text_dto").ExerciseContentTextDto.from_dict(obj)
        if object_type ==  'ExerciseContentVideoDto':
            return import_module("openapi_client.models.exercise_content_video_dto").ExerciseContentVideoDto.from_dict(obj)

        raise ValueError("ExerciseContentDto failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


