# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .exercise_input_dto import ExerciseInputDto
from .select_option_input_base_option import SelectOptionInputBaseOption
from .select_options_input_feedback_dto import SelectOptionsInputFeedbackDto
from typing import Optional, Set
from typing_extensions import Self

class ExerciseInputSelectOptionsDto(ExerciseInputDto):
    """
    ExerciseInputSelectOptionsDto
    """ # noqa: E501
    options: Optional[List[SelectOptionInputBaseOption]] = None
    option_type: Optional[StrictStr] = Field(default=None, alias="optionType")
    value: Optional[StrictStr] = None
    feedback: Optional[SelectOptionsInputFeedbackDto] = None
    __properties: ClassVar[List[str]] = ["id", "type", "sessionId", "options", "optionType", "value", "feedback"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExerciseInputSelectOptionsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of feedback
        if self.feedback:
            _dict['feedback'] = self.feedback.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExerciseInputSelectOptionsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "sessionId": obj.get("sessionId"),
            "options": [SelectOptionInputBaseOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "optionType": obj.get("optionType"),
            "value": obj.get("value"),
            "feedback": SelectOptionsInputFeedbackDto.from_dict(obj["feedback"]) if obj.get("feedback") is not None else None
        })
        return _obj


