# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from .flashcard_content_audio_dto import FlashcardContentAudioDto
from .flashcard_content_dto import FlashcardContentDto
from .flashcard_content_image_dto import FlashcardContentImageDto
from .flashcard_content_text_dto import FlashcardContentTextDto
from .flashcard_content_upload_audio_dto import FlashcardContentUploadAudioDto
from .flashcard_content_upload_image_dto import FlashcardContentUploadImageDto
from .flashcard_content_upload_video_dto import FlashcardContentUploadVideoDto
from .flashcard_content_video_dto import FlashcardContentVideoDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FLASHCARDDTOFRONTCONTENT_ONE_OF_SCHEMAS = ["FlashcardContentAudioDto", "FlashcardContentDto", "FlashcardContentImageDto", "FlashcardContentTextDto", "FlashcardContentUploadAudioDto", "FlashcardContentUploadImageDto", "FlashcardContentUploadVideoDto", "FlashcardContentVideoDto"]

class FlashcardDtoFrontContent(BaseModel):
    """
    FlashcardDtoFrontContent
    """
    # data type: FlashcardContentDto
    oneof_schema_1_validator: Optional[FlashcardContentDto] = None
    # data type: FlashcardContentAudioDto
    oneof_schema_2_validator: Optional[FlashcardContentAudioDto] = None
    # data type: FlashcardContentImageDto
    oneof_schema_3_validator: Optional[FlashcardContentImageDto] = None
    # data type: FlashcardContentTextDto
    oneof_schema_4_validator: Optional[FlashcardContentTextDto] = None
    # data type: FlashcardContentUploadAudioDto
    oneof_schema_5_validator: Optional[FlashcardContentUploadAudioDto] = None
    # data type: FlashcardContentUploadImageDto
    oneof_schema_6_validator: Optional[FlashcardContentUploadImageDto] = None
    # data type: FlashcardContentUploadVideoDto
    oneof_schema_7_validator: Optional[FlashcardContentUploadVideoDto] = None
    # data type: FlashcardContentVideoDto
    oneof_schema_8_validator: Optional[FlashcardContentVideoDto] = None
    actual_instance: Optional[Union[FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto]] = None
    one_of_schemas: Set[str] = { "FlashcardContentAudioDto", "FlashcardContentDto", "FlashcardContentImageDto", "FlashcardContentTextDto", "FlashcardContentUploadAudioDto", "FlashcardContentUploadImageDto", "FlashcardContentUploadVideoDto", "FlashcardContentVideoDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FlashcardDtoFrontContent.model_construct()
        error_messages = []
        match = 0
        # validate data type: FlashcardContentDto
        if not isinstance(v, FlashcardContentDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentDto`")
        else:
            match += 1
        # validate data type: FlashcardContentAudioDto
        if not isinstance(v, FlashcardContentAudioDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentAudioDto`")
        else:
            match += 1
        # validate data type: FlashcardContentImageDto
        if not isinstance(v, FlashcardContentImageDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentImageDto`")
        else:
            match += 1
        # validate data type: FlashcardContentTextDto
        if not isinstance(v, FlashcardContentTextDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentTextDto`")
        else:
            match += 1
        # validate data type: FlashcardContentUploadAudioDto
        if not isinstance(v, FlashcardContentUploadAudioDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentUploadAudioDto`")
        else:
            match += 1
        # validate data type: FlashcardContentUploadImageDto
        if not isinstance(v, FlashcardContentUploadImageDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentUploadImageDto`")
        else:
            match += 1
        # validate data type: FlashcardContentUploadVideoDto
        if not isinstance(v, FlashcardContentUploadVideoDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentUploadVideoDto`")
        else:
            match += 1
        # validate data type: FlashcardContentVideoDto
        if not isinstance(v, FlashcardContentVideoDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FlashcardContentVideoDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FlashcardDtoFrontContent with oneOf schemas: FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FlashcardDtoFrontContent with oneOf schemas: FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FlashcardContentDto
        try:
            instance.actual_instance = FlashcardContentDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentAudioDto
        try:
            instance.actual_instance = FlashcardContentAudioDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentImageDto
        try:
            instance.actual_instance = FlashcardContentImageDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentTextDto
        try:
            instance.actual_instance = FlashcardContentTextDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentUploadAudioDto
        try:
            instance.actual_instance = FlashcardContentUploadAudioDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentUploadImageDto
        try:
            instance.actual_instance = FlashcardContentUploadImageDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentUploadVideoDto
        try:
            instance.actual_instance = FlashcardContentUploadVideoDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FlashcardContentVideoDto
        try:
            instance.actual_instance = FlashcardContentVideoDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FlashcardDtoFrontContent with oneOf schemas: FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FlashcardDtoFrontContent with oneOf schemas: FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FlashcardContentAudioDto, FlashcardContentDto, FlashcardContentImageDto, FlashcardContentTextDto, FlashcardContentUploadAudioDto, FlashcardContentUploadImageDto, FlashcardContentUploadVideoDto, FlashcardContentVideoDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


