# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from .configuration_dto import ConfigurationDto
from .configuration_google_speech_to_text_dto import ConfigurationGoogleSpeechToTextDto
from .configuration_google_text_to_speech_dto import ConfigurationGoogleTextToSpeechDto
from .configuration_google_translate_dto import ConfigurationGoogleTranslateDto
from .configuration_microsoft_text_to_speech_dto import ConfigurationMicrosoftTextToSpeechDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GETCONFIGBYID200RESPONSE_ONE_OF_SCHEMAS = ["ConfigurationDto", "ConfigurationGoogleSpeechToTextDto", "ConfigurationGoogleTextToSpeechDto", "ConfigurationGoogleTranslateDto", "ConfigurationMicrosoftTextToSpeechDto"]

class GetConfigById200Response(BaseModel):
    """
    GetConfigById200Response
    """
    # data type: ConfigurationDto
    oneof_schema_1_validator: Optional[ConfigurationDto] = None
    # data type: ConfigurationGoogleSpeechToTextDto
    oneof_schema_2_validator: Optional[ConfigurationGoogleSpeechToTextDto] = None
    # data type: ConfigurationGoogleTextToSpeechDto
    oneof_schema_3_validator: Optional[ConfigurationGoogleTextToSpeechDto] = None
    # data type: ConfigurationGoogleTranslateDto
    oneof_schema_4_validator: Optional[ConfigurationGoogleTranslateDto] = None
    # data type: ConfigurationMicrosoftTextToSpeechDto
    oneof_schema_5_validator: Optional[ConfigurationMicrosoftTextToSpeechDto] = None
    actual_instance: Optional[Union[ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto]] = None
    one_of_schemas: Set[str] = { "ConfigurationDto", "ConfigurationGoogleSpeechToTextDto", "ConfigurationGoogleTextToSpeechDto", "ConfigurationGoogleTranslateDto", "ConfigurationMicrosoftTextToSpeechDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GetConfigById200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: ConfigurationDto
        if not isinstance(v, ConfigurationDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConfigurationDto`")
        else:
            match += 1
        # validate data type: ConfigurationGoogleSpeechToTextDto
        if not isinstance(v, ConfigurationGoogleSpeechToTextDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConfigurationGoogleSpeechToTextDto`")
        else:
            match += 1
        # validate data type: ConfigurationGoogleTextToSpeechDto
        if not isinstance(v, ConfigurationGoogleTextToSpeechDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConfigurationGoogleTextToSpeechDto`")
        else:
            match += 1
        # validate data type: ConfigurationGoogleTranslateDto
        if not isinstance(v, ConfigurationGoogleTranslateDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConfigurationGoogleTranslateDto`")
        else:
            match += 1
        # validate data type: ConfigurationMicrosoftTextToSpeechDto
        if not isinstance(v, ConfigurationMicrosoftTextToSpeechDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConfigurationMicrosoftTextToSpeechDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GetConfigById200Response with oneOf schemas: ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GetConfigById200Response with oneOf schemas: ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ConfigurationDto
        try:
            instance.actual_instance = ConfigurationDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConfigurationGoogleSpeechToTextDto
        try:
            instance.actual_instance = ConfigurationGoogleSpeechToTextDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConfigurationGoogleTextToSpeechDto
        try:
            instance.actual_instance = ConfigurationGoogleTextToSpeechDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConfigurationGoogleTranslateDto
        try:
            instance.actual_instance = ConfigurationGoogleTranslateDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConfigurationMicrosoftTextToSpeechDto
        try:
            instance.actual_instance = ConfigurationMicrosoftTextToSpeechDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GetConfigById200Response with oneOf schemas: ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GetConfigById200Response with oneOf schemas: ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ConfigurationDto, ConfigurationGoogleSpeechToTextDto, ConfigurationGoogleTextToSpeechDto, ConfigurationGoogleTranslateDto, ConfigurationMicrosoftTextToSpeechDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


