# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.exercise_input_arrange_text_options_dto import ExerciseInputArrangeTextOptionsDto
from openapi_client.models.exercise_input_dto import ExerciseInputDto
from openapi_client.models.exercise_input_pair_options_dto import ExerciseInputPairOptionsDto
from openapi_client.models.exercise_input_record_audio_dto import ExerciseInputRecordAudioDto
from openapi_client.models.exercise_input_record_video_dto import ExerciseInputRecordVideoDto
from openapi_client.models.exercise_input_select_options_dto import ExerciseInputSelectOptionsDto
from openapi_client.models.exercise_input_select_placeholders_dto import ExerciseInputSelectPlaceholdersDto
from openapi_client.models.exercise_input_select_review_options_dto import ExerciseInputSelectReviewOptionsDto
from openapi_client.models.exercise_input_write_placeholders_dto import ExerciseInputWritePlaceholdersDto
from openapi_client.models.exercise_input_write_text_dto import ExerciseInputWriteTextDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SUBMITANSWERREQUEST_ONE_OF_SCHEMAS = ["ExerciseInputArrangeTextOptionsDto", "ExerciseInputDto", "ExerciseInputPairOptionsDto", "ExerciseInputRecordAudioDto", "ExerciseInputRecordVideoDto", "ExerciseInputSelectOptionsDto", "ExerciseInputSelectPlaceholdersDto", "ExerciseInputSelectReviewOptionsDto", "ExerciseInputWritePlaceholdersDto", "ExerciseInputWriteTextDto"]

class SubmitAnswerRequest(BaseModel):
    """
    SubmitAnswerRequest
    """
    # data type: ExerciseInputDto
    oneof_schema_1_validator: Optional[ExerciseInputDto] = None
    # data type: ExerciseInputArrangeTextOptionsDto
    oneof_schema_2_validator: Optional[ExerciseInputArrangeTextOptionsDto] = None
    # data type: ExerciseInputPairOptionsDto
    oneof_schema_3_validator: Optional[ExerciseInputPairOptionsDto] = None
    # data type: ExerciseInputRecordAudioDto
    oneof_schema_4_validator: Optional[ExerciseInputRecordAudioDto] = None
    # data type: ExerciseInputRecordVideoDto
    oneof_schema_5_validator: Optional[ExerciseInputRecordVideoDto] = None
    # data type: ExerciseInputSelectOptionsDto
    oneof_schema_6_validator: Optional[ExerciseInputSelectOptionsDto] = None
    # data type: ExerciseInputSelectPlaceholdersDto
    oneof_schema_7_validator: Optional[ExerciseInputSelectPlaceholdersDto] = None
    # data type: ExerciseInputSelectReviewOptionsDto
    oneof_schema_8_validator: Optional[ExerciseInputSelectReviewOptionsDto] = None
    # data type: ExerciseInputWritePlaceholdersDto
    oneof_schema_9_validator: Optional[ExerciseInputWritePlaceholdersDto] = None
    # data type: ExerciseInputWriteTextDto
    oneof_schema_10_validator: Optional[ExerciseInputWriteTextDto] = None
    actual_instance: Optional[Union[ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto]] = None
    one_of_schemas: Set[str] = { "ExerciseInputArrangeTextOptionsDto", "ExerciseInputDto", "ExerciseInputPairOptionsDto", "ExerciseInputRecordAudioDto", "ExerciseInputRecordVideoDto", "ExerciseInputSelectOptionsDto", "ExerciseInputSelectPlaceholdersDto", "ExerciseInputSelectReviewOptionsDto", "ExerciseInputWritePlaceholdersDto", "ExerciseInputWriteTextDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SubmitAnswerRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExerciseInputDto
        if not isinstance(v, ExerciseInputDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputDto`")
        else:
            match += 1
        # validate data type: ExerciseInputArrangeTextOptionsDto
        if not isinstance(v, ExerciseInputArrangeTextOptionsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputArrangeTextOptionsDto`")
        else:
            match += 1
        # validate data type: ExerciseInputPairOptionsDto
        if not isinstance(v, ExerciseInputPairOptionsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputPairOptionsDto`")
        else:
            match += 1
        # validate data type: ExerciseInputRecordAudioDto
        if not isinstance(v, ExerciseInputRecordAudioDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputRecordAudioDto`")
        else:
            match += 1
        # validate data type: ExerciseInputRecordVideoDto
        if not isinstance(v, ExerciseInputRecordVideoDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputRecordVideoDto`")
        else:
            match += 1
        # validate data type: ExerciseInputSelectOptionsDto
        if not isinstance(v, ExerciseInputSelectOptionsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputSelectOptionsDto`")
        else:
            match += 1
        # validate data type: ExerciseInputSelectPlaceholdersDto
        if not isinstance(v, ExerciseInputSelectPlaceholdersDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputSelectPlaceholdersDto`")
        else:
            match += 1
        # validate data type: ExerciseInputSelectReviewOptionsDto
        if not isinstance(v, ExerciseInputSelectReviewOptionsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputSelectReviewOptionsDto`")
        else:
            match += 1
        # validate data type: ExerciseInputWritePlaceholdersDto
        if not isinstance(v, ExerciseInputWritePlaceholdersDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputWritePlaceholdersDto`")
        else:
            match += 1
        # validate data type: ExerciseInputWriteTextDto
        if not isinstance(v, ExerciseInputWriteTextDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseInputWriteTextDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SubmitAnswerRequest with oneOf schemas: ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SubmitAnswerRequest with oneOf schemas: ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ExerciseInputDto
        try:
            instance.actual_instance = ExerciseInputDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputArrangeTextOptionsDto
        try:
            instance.actual_instance = ExerciseInputArrangeTextOptionsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputPairOptionsDto
        try:
            instance.actual_instance = ExerciseInputPairOptionsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputRecordAudioDto
        try:
            instance.actual_instance = ExerciseInputRecordAudioDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputRecordVideoDto
        try:
            instance.actual_instance = ExerciseInputRecordVideoDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputSelectOptionsDto
        try:
            instance.actual_instance = ExerciseInputSelectOptionsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputSelectPlaceholdersDto
        try:
            instance.actual_instance = ExerciseInputSelectPlaceholdersDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputSelectReviewOptionsDto
        try:
            instance.actual_instance = ExerciseInputSelectReviewOptionsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputWritePlaceholdersDto
        try:
            instance.actual_instance = ExerciseInputWritePlaceholdersDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseInputWriteTextDto
        try:
            instance.actual_instance = ExerciseInputWriteTextDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SubmitAnswerRequest with oneOf schemas: ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SubmitAnswerRequest with oneOf schemas: ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExerciseInputArrangeTextOptionsDto, ExerciseInputDto, ExerciseInputPairOptionsDto, ExerciseInputRecordAudioDto, ExerciseInputRecordVideoDto, ExerciseInputSelectOptionsDto, ExerciseInputSelectPlaceholdersDto, ExerciseInputSelectReviewOptionsDto, ExerciseInputWritePlaceholdersDto, ExerciseInputWriteTextDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


