# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.exercise_session_options_learn_flashcards_dto import ExerciseSessionOptionsLearnFlashcardsDto
from openapi_client.models.exercise_session_options_review_flashcards_dto import ExerciseSessionOptionsReviewFlashcardsDto
from openapi_client.models.exercise_session_options_select_flashcards_dto import ExerciseSessionOptionsSelectFlashcardsDto
from openapi_client.models.exercise_session_options_write_flashcards_dto import ExerciseSessionOptionsWriteFlashcardsDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

UPDATECONFIGREQUEST_ONE_OF_SCHEMAS = ["ExerciseSessionOptionsLearnFlashcardsDto", "ExerciseSessionOptionsReviewFlashcardsDto", "ExerciseSessionOptionsSelectFlashcardsDto", "ExerciseSessionOptionsWriteFlashcardsDto"]

class UpdateConfigRequest(BaseModel):
    """
    UpdateConfigRequest
    """
    # data type: ExerciseSessionOptionsLearnFlashcardsDto
    oneof_schema_1_validator: Optional[ExerciseSessionOptionsLearnFlashcardsDto] = None
    # data type: ExerciseSessionOptionsReviewFlashcardsDto
    oneof_schema_2_validator: Optional[ExerciseSessionOptionsReviewFlashcardsDto] = None
    # data type: ExerciseSessionOptionsSelectFlashcardsDto
    oneof_schema_3_validator: Optional[ExerciseSessionOptionsSelectFlashcardsDto] = None
    # data type: ExerciseSessionOptionsWriteFlashcardsDto
    oneof_schema_4_validator: Optional[ExerciseSessionOptionsWriteFlashcardsDto] = None
    actual_instance: Optional[Union[ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto]] = None
    one_of_schemas: Set[str] = { "ExerciseSessionOptionsLearnFlashcardsDto", "ExerciseSessionOptionsReviewFlashcardsDto", "ExerciseSessionOptionsSelectFlashcardsDto", "ExerciseSessionOptionsWriteFlashcardsDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UpdateConfigRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExerciseSessionOptionsLearnFlashcardsDto
        if not isinstance(v, ExerciseSessionOptionsLearnFlashcardsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseSessionOptionsLearnFlashcardsDto`")
        else:
            match += 1
        # validate data type: ExerciseSessionOptionsReviewFlashcardsDto
        if not isinstance(v, ExerciseSessionOptionsReviewFlashcardsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseSessionOptionsReviewFlashcardsDto`")
        else:
            match += 1
        # validate data type: ExerciseSessionOptionsSelectFlashcardsDto
        if not isinstance(v, ExerciseSessionOptionsSelectFlashcardsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseSessionOptionsSelectFlashcardsDto`")
        else:
            match += 1
        # validate data type: ExerciseSessionOptionsWriteFlashcardsDto
        if not isinstance(v, ExerciseSessionOptionsWriteFlashcardsDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExerciseSessionOptionsWriteFlashcardsDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UpdateConfigRequest with oneOf schemas: ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UpdateConfigRequest with oneOf schemas: ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ExerciseSessionOptionsLearnFlashcardsDto
        try:
            instance.actual_instance = ExerciseSessionOptionsLearnFlashcardsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseSessionOptionsReviewFlashcardsDto
        try:
            instance.actual_instance = ExerciseSessionOptionsReviewFlashcardsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseSessionOptionsSelectFlashcardsDto
        try:
            instance.actual_instance = ExerciseSessionOptionsSelectFlashcardsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExerciseSessionOptionsWriteFlashcardsDto
        try:
            instance.actual_instance = ExerciseSessionOptionsWriteFlashcardsDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UpdateConfigRequest with oneOf schemas: ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UpdateConfigRequest with oneOf schemas: ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExerciseSessionOptionsLearnFlashcardsDto, ExerciseSessionOptionsReviewFlashcardsDto, ExerciseSessionOptionsSelectFlashcardsDto, ExerciseSessionOptionsWriteFlashcardsDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


